# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      displayName: Maven Build
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: ACR build
      inputs:
        containerRegistry: 'KundenplattformACR'
        #repository: 'maeddes/monolith-todo'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: ACR push
      inputs:
        containerRegistry: 'KundenplattformACR'
        #repository: 'maeddes/monolith-todo'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: DockerHub build and push
      inputs:
        containerRegistry: 'DockerHub Matthias'
        repository: 'maeddes/monolith-todo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'