apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: todo-app
  name: todo-db
  labels:
    app: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: matthias
        - name: MYSQL_PASSWORD
          value: matthias
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_ROOT_PASSWORD
          value: passw0rd
        ports:
        - containerPort: 3306
          name: mysql

